language: cpp
compiler: clang++
python: 
  - '3.5'
install:
  - pip install --user codecov
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - libclang-5.0-dev
script: 
  - make force_cover_coverage
  - ./force_cover examples/example.cc -- > testing/observed_example.cc
  - diff testing/observed_example.cc testing/expected_outputs/example.cc
  - clang++ testing/observed_example.cc -fprofile-instr-generate -fcoverage-mapping -o testing/observed_example
  - cd testing && ./observed_example
  - llvm-profdata merge default.profraw -o default.profdata
  - llvm-cov show observed_example -instr-profile=default.profdata > example_coverage.txt
  - cd ..
  - coverage run fix_coverage.py testing/example_coverage.txt
  - diff testing/example_coverage.txt testing/expected_outputs/example_coverage.txt
  - rm testing/example_coverage.txt
  - cp examples/complex_coverage_report.txt testing
  - coverage run fix_coverage.py testing/complex_coverage_report.txt
  - diff testing/complex_coverage_report.txt testing/expected_outputs/complex_coverage_report.txt
  - rm testing/complex_coverage_report.txt testing/expected_outputs/complex_coverage_report.txt examples/coverage_test_tools.txt
after_success:
  - codecov
  - llvm-profdata merge default.profraw -o default.profdata
  - llvm-cov show ./force_cover -instr-profile=default.profdata > coverage.txt
  - bash <(curl -s https://codecov.io/bash)