language: cpp
compiler: clang++
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - libclang-5.0-dev
env:
  CXX=clang++-5.0
  CC=clang-5.0
  LLVM_SRC_PATH=/usr/lib/llvm-5.0

script: make
